"""add context documents and chunks

Revision ID: 3618b1d7fdbc
Revises: 4211eb437cf0
Create Date: 2026-04-02 13:10:37.559714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '3618b1d7fdbc'
down_revision: Union[str, Sequence[str], None] = '4211eb437cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_short_code', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_documents_document_short_code'), 'context_documents', ['document_short_code'], unique=False)
    op.create_index(op.f('ix_context_documents_source_type'), 'context_documents', ['source_type'], unique=False)
    op.create_table('context_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column("embedding", VECTOR(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['context_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_chunks_document_id'), 'context_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_chunks_document_id'), table_name='context_chunks')
    op.drop_table('context_chunks')
    op.drop_index(op.f('ix_context_documents_source_type'), table_name='context_documents')
    op.drop_index(op.f('ix_context_documents_document_short_code'), table_name='context_documents')
    op.drop_table('context_documents')
    # ### end Alembic commands ###
