"""add section embeddings

Revision ID: 4ee563ba8b97
Revises: b84db1b1e05d
Create Date: 2026-04-02 11:43:02.248992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '4ee563ba8b97'
down_revision: Union[str, Sequence[str], None] = 'b84db1b1e05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "regulation_sections",
    sa.Column("embedding", VECTOR(1536), nullable=True),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_sections', 'embedding')
    # ### end Alembic commands ###
