"""add impact_analyses table

Revision ID: 8228100901ac
Revises: 81951231fba7
Create Date: 2026-04-02 12:39:39.837886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8228100901ac'
down_revision: Union[str, Sequence[str], None] = '81951231fba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('what_changed', sa.Text(), nullable=False),
    sa.Column('affected_functions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('affected_processes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('recommended_action', sa.String(length=20), nullable=True),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_analyses_change_id'), 'impact_analyses', ['change_id'], unique=True)
    op.drop_index(op.f('idx_sections_embedding'), table_name='regulation_sections', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sections_embedding'), 'regulation_sections', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_impact_analyses_change_id'), table_name='impact_analyses')
    op.drop_table('impact_analyses')
    # ### end Alembic commands ###
