"""add changes table

Revision ID: b84db1b1e05d
Revises: 5fa916ef0201
Create Date: 2026-04-02 11:32:59.096502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84db1b1e05d'
down_revision: Union[str, Sequence[str], None] = '5fa916ef0201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_short_code', sa.String(length=30), nullable=False),
    sa.Column('section_number', sa.String(length=30), nullable=False),
    sa.Column('old_part_id', sa.Integer(), nullable=True),
    sa.Column('new_part_id', sa.Integer(), nullable=True),
    sa.Column('old_date', sa.Date(), nullable=False),
    sa.Column('new_date', sa.Date(), nullable=False),
    sa.Column('raw_diff', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=15), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_part_id'], ['regulation_parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_part_id'], ['regulation_parts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_short_code', 'section_number', 'old_date', 'new_date', name='uq_change_section_dates')
    )
    op.create_index(op.f('ix_changes_document_short_code'), 'changes', ['document_short_code'], unique=False)
    op.create_index(op.f('ix_changes_new_date'), 'changes', ['new_date'], unique=False)
    op.create_index(op.f('ix_changes_new_part_id'), 'changes', ['new_part_id'], unique=False)
    op.create_index(op.f('ix_changes_old_date'), 'changes', ['old_date'], unique=False)
    op.create_index(op.f('ix_changes_old_part_id'), 'changes', ['old_part_id'], unique=False)
    op.create_index(op.f('ix_changes_section_number'), 'changes', ['section_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changes_section_number'), table_name='changes')
    op.drop_index(op.f('ix_changes_old_part_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_old_date'), table_name='changes')
    op.drop_index(op.f('ix_changes_new_part_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_new_date'), table_name='changes')
    op.drop_index(op.f('ix_changes_document_short_code'), table_name='changes')
    op.drop_table('changes')
    # ### end Alembic commands ###
