"""add uniqueness constraints

Revision ID: e19ea19bea1b
Revises: fc223ac0bc45
Create Date: 2026-04-02 02:11:31.634538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19ea19bea1b'
down_revision: Union[str, Sequence[str], None] = 'fc223ac0bc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_regulation_parts_title_part_version', 'regulation_parts', ['title_number', 'part_number', 'version_date'])
    op.create_unique_constraint('uq_regulation_sections_part_id_section_number', 'regulation_sections', ['part_id', 'section_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_regulation_sections_part_id_section_number', 'regulation_sections', type_='unique')
    op.drop_constraint('uq_regulation_parts_title_part_version', 'regulation_parts', type_='unique')
    # ### end Alembic commands ###
