"""create regulation tables

Revision ID: fc223ac0bc45
Revises: 
Create Date: 2026-04-02 01:26:25.793360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc223ac0bc45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulation_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_number', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('version_date', sa.Date(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulation_parts_part_number'), 'regulation_parts', ['part_number'], unique=False)
    op.create_index(op.f('ix_regulation_parts_title_number'), 'regulation_parts', ['title_number'], unique=False)
    op.create_index(op.f('ix_regulation_parts_version_date'), 'regulation_parts', ['version_date'], unique=False)
    op.create_table('regulation_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_section_number', sa.String(length=200), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('version_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['regulation_parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulation_sections_part_id'), 'regulation_sections', ['part_id'], unique=False)
    op.create_index(op.f('ix_regulation_sections_section_number'), 'regulation_sections', ['section_number'], unique=False)
    op.create_index(op.f('ix_regulation_sections_version_date'), 'regulation_sections', ['version_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulation_sections_version_date'), table_name='regulation_sections')
    op.drop_index(op.f('ix_regulation_sections_section_number'), table_name='regulation_sections')
    op.drop_index(op.f('ix_regulation_sections_part_id'), table_name='regulation_sections')
    op.drop_table('regulation_sections')
    op.drop_index(op.f('ix_regulation_parts_version_date'), table_name='regulation_parts')
    op.drop_index(op.f('ix_regulation_parts_title_number'), table_name='regulation_parts')
    op.drop_index(op.f('ix_regulation_parts_part_number'), table_name='regulation_parts')
    op.drop_table('regulation_parts')
    # ### end Alembic commands ###
